PicManager/Models/AlbumContext.cs
namespace PicManager
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class AlbumContext : DbContext
    {
        public AlbumContext()
            : base("name=AlbumContext")
        {
        }

        public virtual DbSet<Image> Images { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Image>()
                .Property(e => e.Extension)
                .IsUnicode(false);
        }
    }
}

PicManager/Models/IAlbumManager.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PicManager.Models
{
    interface IAlbumManager
    {
        // Проверка на содержимое БД
        bool IsEmpty();

        // Получение всех изображений из БД
        Image[] GetImages();

        // Добавление записи об изображении в БД
        void AddImage(string iName, string iExt, string iPath);

        // Удаление записи об изображении в БД
        void RemoveImage(string iName, string iId);

    }
}

PicManager/Models/Image.cs
namespace PicManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Image
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Filename { get; set; }

        [Required]
        public string Filepath { get; set; }

        [Required]
        [StringLength(10)]
        public string Extension { get; set; }
    }
}

PicManager/Models/OrdinaryAlbumManager.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PicManager.Models
{
    public class OrdinaryAlbumManager : IAlbumManager
    {
        public OrdinaryAlbumManager()
        {}

        public Image[] GetImages()
        {
            using (var cont = new AlbumContext())
            {
                List<object> img_list = new List<object>();
                var result = cont.Set<Image>().ToArray();

                if (result.Count() == 0 || result.Any() == false)
                    return null;

                return result.ToArray();
            }
        }

        public void AddImage(string iName, string iExt, string iPath)
        {
            using (var cont = new AlbumContext())
            {
                cont.Set<Image>().Add(new Image { Filename = iName, Extension = iExt, Filepath = iPath });
                cont.SaveChanges();
            }
        }

        public void RemoveImage(string iName, string iId)
        {
            using (var cont = new AlbumContext())
            {
                int id = Convert.ToInt32(iId);
                var found = from img in cont.Set<Image>() where img.Id == id && img.Filename == iName select img;

                if (found.Count() == 0 || found.Any() == false)
                    return;
                else
                {
                    cont.Set<Image>().Remove(found.First());
                    cont.SaveChanges();
                }
            }
        }

        public bool IsEmpty()
        {
            using (var cont = new AlbumContext())
            {
                int imgcount = cont.Images.Count();

                if (imgcount > 0)
                    return false;
                else
                    return true;
            }
        }
    }
}

PicManager/Models/UploadedFileWrap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PicManager.Models
{
    // "Обертка" для хранения данных о подгруженном изображении
    public class UploadedFileWrap
    {
        [Required]
        public HttpPostedFileBase UploadedFile { get; set; } // загруженный файл

        [Required]
        public string FileName { get; set; } // имя файла (введенное вручную)

        public string FileExtension { get; set; } // расширение файла

        public string FilePath { get; set; } // путь к файлу (для отображения и хранения в БД)
    }
}

PicManager/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PicManager.Models;
using System.IO;

namespace PicManager.Controllers
{
    public class AlbumController : Controller
    {
        // для операций с БД
        IAlbumManager mng;

        [HttpGet]
        public ActionResult Images()
        {
            return View(new UploadedFileWrap());
        }

        [HttpPost]
        public ActionResult Images(UploadedFileWrap fw, string fId, string fName, string fPath)
        {
            if (ModelState.IsValid)
            {
                UploadImage(fw);
                return View(new UploadedFileWrap());
            }
            else
            {
                return View(new UploadedFileWrap());
            }
        }

        // Метод для возвращения partialview с содержимым галереи
        public ActionResult AlbumContent()
        {
            mng = new OrdinaryAlbumManager();
            if (mng.IsEmpty())
                return Content("Album is empty. You can upload something!");
            else
            {
                var imgs = mng.GetImages();
                return PartialView("AlbumContent",imgs);
            }
        }

        [HttpPost]
        public ActionResult RemoveImage(string fId, string fName, string fPath)
        {
            mng = new OrdinaryAlbumManager();
            var actualpath = Server.MapPath(fPath); // физическое расположение картинки

            if (System.IO.File.Exists(actualpath))
            {
                mng.RemoveImage(fName, fId);
                System.IO.File.Delete(actualpath);
            }

            return RedirectToAction("Images");
        }

        // Загрузка изображения на сервер
        private void UploadImage(UploadedFileWrap fw)
        {
            mng = new OrdinaryAlbumManager();

            fw.FileExtension = GetFileExtension(fw);

            // костыль для проверки расширения загружаемого файла
            if (fw.FileExtension == ".jpg" || fw.FileExtension == ".png" || fw.FileExtension == ".gif" || fw.FileExtension == ".jpeg")
            {
                fw.FilePath = string.Format("/Content/usr_pics/{0}{1}", fw.FileName, fw.FileExtension);

                string actualpath = Server.MapPath(fw.FilePath); // физическое расположение картинки
                fw.UploadedFile.SaveAs(actualpath);
                mng.AddImage(fw.FileName, fw.FileExtension, fw.FilePath);
            }
        }

        // Удаление изображения с сервера (БД и папки)
        private void DeleteImage(string fId, string fName, string fPath)
        {
            mng = new OrdinaryAlbumManager();
            var actualpath = Server.MapPath(fPath);

            if (System.IO.File.Exists(actualpath))
            {
                mng.RemoveImage(fName, fId);
                System.IO.File.Delete(actualpath);
            }
        }

        // Получение расширения загруженного файла
        private string GetFileExtension(UploadedFileWrap fWrap)
        {
            string ctype = fWrap.UploadedFile.ContentType;
            int sep_pos = ctype.IndexOf('/');
            string ext = "." + ctype.Substring(sep_pos + 1);
            return ext;
        }
    }
}

PicManager/Views/Album/AlbumContent.cshtml
@model Image[]
<div class="album_layer">
    @for(int i=0;i<Model.Length;i++)
    {
        <div class="img_container">
            @using (Html.BeginForm("RemoveImage", "Album",
                    new
                    {
                        fId = Model[i].Id,
                        fName = Model[i].Filename,
                        fPath = Model[i].Filepath
                    }, FormMethod.Post))
            {
                <a data-toggle="modal" data-target="#dlg_fullsize_@i">
                    <img src="@Model[i].Filepath" />
                    <h6>@Model[i].Filename</h6>
                </a>
                <div hidden="hidden">@Model[i].Id</div>
                <button type="submit" class="btn btn-xs">Delete</button>
            }

            <div class="modal fade" role="dialog" id="dlg_fullsize_@i">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3>Preview</h3>
                        </div>
                        <div class="modal-body">
                            <img src="@Model[i].Filepath" />
                        </div>
                        <div class="modal-footer">
                            <h4>@Model[i].Filename</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

PicManager/Views/Album/Images.cshtml
@model PicManager.Models.UploadedFileWrap
@{
    ViewBag.Title = "Images";
}
<script src="~/Scripts/bootstrap.min.js"></script>
<section class="album_content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Gallery</h4>
        </div>
        <div class="panel-body">
            @Html.Action("AlbumContent", "Album")
        </div>
    </div>
</section>
<aside class="sidepanel">
    <h4>Control panel</h4>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#dlg_upload">Upload image</button>
    <div id="dlg_upload" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Uploading</h4>
                </div>
                <div class="modal-body">
                    <p>Select file to upload (Size must be less than 4 MB)</p>
                    @using (Html.BeginForm("Images", "Album", FormMethod.Post, new { enctype = "multipart/form-data"} ))
                    {
                        @Html.ValidationSummary()
                        @Html.TextBoxFor(m => m.FileName, new {@class = "input-sm", @placeholder = "Type filename here...", @id = "txtfield" })
                        <input type="file" name="UploadedFile" class="input-xlarge"/>
                    <input type="submit" class="btn btn-success" value="Save" />
                    }
                </div>
            </div>
        </div>
    </div>
</aside>

PicManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <header>
        <div class="logobox">
            <img src="~/Content/logo.png" />
            <span>My Pocket Album</span>
        </div>
    </header>
    <div class="wrap">
        @RenderBody()
    </div>
</body>
</html>